language: ruby

services:
  - postgresql
  - redis-server
  - elasticsearch

rvm:
  - 2.3.6
  - 2.5.1

env:
  - REDMINE_VER=3.4-stable DB=postgresql
  - REDMINE_VER=4.0-stable DB=postgresql

sudo: true
addons:
  apt:
    packages:
      - oracle-java8-set-default

before_install:
  - sudo service elasticsearch stop
  - export ES_HOME=/usr/share/elasticsearch
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.13.deb
  - sudo dpkg -i --force-confnew elasticsearch-5.6.13.deb
  - sudo $ES_HOME/bin/elasticsearch-plugin install http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/5.6.13/elasticsearch-analysis-morphology-5.6.13.zip
  - yes | sudo $ES_HOME/bin/elasticsearch-plugin install ingest-attachment
  - sudo service elasticsearch start
  - sleep 5

install: "echo skip bundle install"

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_elasticsearch
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - bash -x ./travis.sh
